const apply=()=>{
document.querySelector('.player-info__server-info-bar')?.style.setProperty('--server-flag','url(https://arzfun.github.io/assets/hud/logo_full.png)');
document.querySelector('.player-info__vip-logo') && (document.querySelector('.player-info__vip-logo').src='https://arzfun.github.io/assets/hud/addvip.gif');
const o=new MutationObserver(()=>document.querySelectorAll('.dialog').forEach(el=>el.style.setProperty('--bgColor','181,10,255')));o.observe(document.body,{childList:true,subtree:true});
document.querySelector('.player-info__project-logo-image')&&(document.querySelector('.player-info__project-logo-image').outerHTML=`<video class="player-info__project-logo-image" autoplay muted loop playsinline style="background-color:transparent" src="https://arzfun.github.io/assets/logos/logo_spring.webm"></video>`);
(function(){const m={'d920b253bc63a3af4f94.svg':'https://arzfun.github.io/assets/hud/arzfun-title.png','de38bd41d7d33dbc23d2.svg':'https://arzfun.github.io/assets/hud/arzfun-logo.png'};const r=i=>{if(!i?.src)return;for(const k in m)if(i.src.includes(k))i.src=m[k]};document.querySelectorAll('img').forEach(r);new MutationObserver(e=>e.forEach(t=>t.addedNodes.forEach(n=>{if(n.tagName==='IMG')r(n);if(n.querySelectorAll)n.querySelectorAll('img').forEach(r)}))).observe(document.documentElement,{childList:true,subtree:true})})();
document.addEventListener('click',e=>{const el=e.target.closest('.main-menu-footer__media-link,.main-menu-footer__media-social');if(!el)return;e.stopImmediatePropagation();e.preventDefault();const t=el.innerText.toLowerCase();if(t.includes('сайт'))window.cef.Open('https://arzfun.hhos.net/api/launcher/link?site',1);else if(t.includes('форум'))window.cef.Open('https://arzfun.hhos.net/api/launcher/link?forum',1);else if(el.querySelector('.icon-social-vk'))window.cef.Open('https://arzfun.hhos.net/api/launcher/link?vk',1);else if(el.querySelector('.icon-social-tg'))window.cef.Open('https://arzfun.hhos.net/api/launcher/link?telegram',1);else if(el.querySelector('.icon-social-discord'))window.cef.Open('https://arzfun.hhos.net/api/launcher/link?discord',1);},true);
console.log('[arzfun-hud-patch] applied');
};
document.readyState==='loading'
  ? document.addEventListener('DOMContentLoaded',apply)
  : apply();